/* Auto-generated by surface/specmine/cbmc_oracle.py (Phase 5.3 backward leg). */
/* Asserts the missing mined contract at the wrapped callee's entry; */
/* CBMC reports UNSAFE when a feasible path violates the contract.   */

static int __specmine_rcu_depth = 0;
static int __specmine_rcu_bh_depth = 0;
static int __specmine_rcu_sched_depth = 0;
static int __specmine_mutex_depth = 0;
static int __specmine_spin_depth = 0;

#define rcu_read_lock(...) do { __specmine_rcu_depth++; } while (0)
#define rcu_read_lock_bh(...) do { __specmine_rcu_depth++; } while (0)
#define rcu_read_lock_sched(...) do { __specmine_rcu_depth++; } while (0)
#define rcu_read_unlock(...) do { if (__specmine_rcu_depth > 0) __specmine_rcu_depth--; } while (0)
#define rcu_read_unlock_bh(...) do { if (__specmine_rcu_depth > 0) __specmine_rcu_depth--; } while (0)
#define rcu_read_unlock_sched(...) do { if (__specmine_rcu_depth > 0) __specmine_rcu_depth--; } while (0)
#define mutex_lock(...) do { __specmine_mutex_depth++; } while (0)
#define mutex_lock_nested(...) do { __specmine_mutex_depth++; } while (0)
#define mutex_lock_interruptible(...) do { __specmine_mutex_depth++; } while (0)
#define mutex_lock_killable(...) do { __specmine_mutex_depth++; } while (0)
#define mutex_unlock(...) do { if (__specmine_mutex_depth > 0) __specmine_mutex_depth--; } while (0)
#define spin_lock(...) do { __specmine_spin_depth++; } while (0)
#define spin_lock_bh(...) do { __specmine_spin_depth++; } while (0)
#define spin_lock_irq(...) do { __specmine_spin_depth++; } while (0)
#define spin_lock_irqsave(...) do { __specmine_spin_depth++; } while (0)
#define spin_lock_nested(...) do { __specmine_spin_depth++; } while (0)
#define spin_unlock(...) do { if (__specmine_spin_depth > 0) __specmine_spin_depth--; } while (0)
#define spin_unlock_bh(...) do { if (__specmine_spin_depth > 0) __specmine_spin_depth--; } while (0)
#define spin_unlock_irq(...) do { if (__specmine_spin_depth > 0) __specmine_spin_depth--; } while (0)
#define spin_unlock_irqrestore(...) do { if (__specmine_spin_depth > 0) __specmine_spin_depth--; } while (0)
#define rcu_read_lock_held(...) ((__specmine_rcu_depth) > 0)
#define rcu_read_lock_bh_held(...) ((__specmine_rcu_bh_depth) > 0)
#define rcu_read_lock_sched_held(...) ((__specmine_rcu_sched_depth) > 0)
#define spin_is_locked(...) ((__specmine_spin_depth) > 0)
#define assert_spin_locked(...) ((__specmine_spin_depth) > 0)
#define mutex_is_locked(...) ((__specmine_mutex_depth) > 0)
#define lockdep_assert_held(x) __CPROVER_assume(__specmine_mutex_depth > 0 || __specmine_spin_depth > 0 || __specmine_rcu_depth > 0)
#define lockdep_assert_held_once(x) __CPROVER_assume(__specmine_mutex_depth > 0 || __specmine_spin_depth > 0 || __specmine_rcu_depth > 0)
#define lockdep_assert_held_write(x) __CPROVER_assume(__specmine_mutex_depth > 0 || __specmine_spin_depth > 0 || __specmine_rcu_depth > 0)
#define lockdep_assert_held_read(x) __CPROVER_assume(__specmine_mutex_depth > 0 || __specmine_spin_depth > 0 || __specmine_rcu_depth > 0)
#define lockdep_is_held(x) __CPROVER_assume(__specmine_mutex_depth > 0 || __specmine_spin_depth > 0 || __specmine_rcu_depth > 0)

/* Null / error-state model (Phase 5.6 null_init harness). */
static int __specmine_arg_is_err = 0;
static int __specmine_arg_is_null = 0;

#define IS_ERR(p)           ((__specmine_arg_is_err) != 0)
#define IS_ERR_OR_NULL(p)   ((__specmine_arg_is_err) != 0 || (__specmine_arg_is_null) != 0)
#define IS_ERR_VALUE(p)     ((__specmine_arg_is_err) != 0)
#define PTR_ERR_OR_ZERO(p)  (__specmine_arg_is_err)
#define PTR_ERR(p)          (__specmine_arg_is_err)

/* Nondeterministic int — CBMC enumerates feasible values. */
int nondet_int(void);

static int __specmine_wrap_process_item(int a0) {
    __CPROVER_assert(__specmine_arg_is_err == 0 && __specmine_arg_is_null == 0, "specmine: arg must be non-IS_ERR / non-NULL at process_item entry");
    return 0;
}

static int caller_buggy_null(int item)
{
    return __specmine_wrap_process_item(item);
}

int main(void) {
    int arg0 = (int) nondet_int();
    __specmine_arg_is_err = (int) nondet_int();
    __specmine_arg_is_null = (int) nondet_int();
    (void) caller_buggy_null(arg0);
    return 0;
}
