/* Auto-generated by surface/specmine/cbmc_oracle.py (Phase 5.3 backward leg). */
/* Asserts the missing mined contract at the wrapped callee's entry; */
/* CBMC reports UNSAFE when a feasible path violates the contract.   */

static int __specmine_rcu_depth = 0;
static int __specmine_rcu_bh_depth = 0;
static int __specmine_rcu_sched_depth = 0;
static int __specmine_mutex_depth = 0;
static int __specmine_spin_depth = 0;

#define rcu_read_lock(...) do { __specmine_rcu_depth++; } while (0)
#define rcu_read_lock_bh(...) do { __specmine_rcu_depth++; } while (0)
#define rcu_read_lock_sched(...) do { __specmine_rcu_depth++; } while (0)
#define rcu_read_unlock(...) do { if (__specmine_rcu_depth > 0) __specmine_rcu_depth--; } while (0)
#define rcu_read_unlock_bh(...) do { if (__specmine_rcu_depth > 0) __specmine_rcu_depth--; } while (0)
#define rcu_read_unlock_sched(...) do { if (__specmine_rcu_depth > 0) __specmine_rcu_depth--; } while (0)
#define mutex_lock(...) do { __specmine_mutex_depth++; } while (0)
#define mutex_lock_nested(...) do { __specmine_mutex_depth++; } while (0)
#define mutex_lock_interruptible(...) do { __specmine_mutex_depth++; } while (0)
#define mutex_lock_killable(...) do { __specmine_mutex_depth++; } while (0)
#define mutex_unlock(...) do { if (__specmine_mutex_depth > 0) __specmine_mutex_depth--; } while (0)
#define spin_lock(...) do { __specmine_spin_depth++; } while (0)
#define spin_lock_bh(...) do { __specmine_spin_depth++; } while (0)
#define spin_lock_irq(...) do { __specmine_spin_depth++; } while (0)
#define spin_lock_irqsave(...) do { __specmine_spin_depth++; } while (0)
#define spin_lock_nested(...) do { __specmine_spin_depth++; } while (0)
#define spin_unlock(...) do { if (__specmine_spin_depth > 0) __specmine_spin_depth--; } while (0)
#define spin_unlock_bh(...) do { if (__specmine_spin_depth > 0) __specmine_spin_depth--; } while (0)
#define spin_unlock_irq(...) do { if (__specmine_spin_depth > 0) __specmine_spin_depth--; } while (0)
#define spin_unlock_irqrestore(...) do { if (__specmine_spin_depth > 0) __specmine_spin_depth--; } while (0)
#define rcu_read_lock_held(...) ((__specmine_rcu_depth) > 0)
#define rcu_read_lock_bh_held(...) ((__specmine_rcu_bh_depth) > 0)
#define rcu_read_lock_sched_held(...) ((__specmine_rcu_sched_depth) > 0)
#define spin_is_locked(...) ((__specmine_spin_depth) > 0)
#define assert_spin_locked(...) ((__specmine_spin_depth) > 0)
#define mutex_is_locked(...) ((__specmine_mutex_depth) > 0)
#define lockdep_assert_held(x) __CPROVER_assume(__specmine_mutex_depth > 0 || __specmine_spin_depth > 0 || __specmine_rcu_depth > 0)
#define lockdep_assert_held_once(x) __CPROVER_assume(__specmine_mutex_depth > 0 || __specmine_spin_depth > 0 || __specmine_rcu_depth > 0)
#define lockdep_assert_held_write(x) __CPROVER_assume(__specmine_mutex_depth > 0 || __specmine_spin_depth > 0 || __specmine_rcu_depth > 0)
#define lockdep_assert_held_read(x) __CPROVER_assume(__specmine_mutex_depth > 0 || __specmine_spin_depth > 0 || __specmine_rcu_depth > 0)
#define lockdep_is_held(x) __CPROVER_assume(__specmine_mutex_depth > 0 || __specmine_spin_depth > 0 || __specmine_rcu_depth > 0)

/* Nondeterministic int — CBMC enumerates feasible values. */
int nondet_int(void);

static int __specmine_wrap_lookup_thing(int a0) {
    __CPROVER_assert(__specmine_rcu_depth > 0, "specmine: rcu_read_lock_held must hold at lookup_thing entry");
    return 0;
}

static int caller_loopy_buggy(int n)
{
    int i, r = 0;
    for (i = 0; i < n; i++) {
        r += __specmine_wrap_lookup_thing(i);
    }
    return r;
}

int main(void) {
    int arg0 = (int) nondet_int();
    /* Phase 5.5 refinement preconditions */
    __CPROVER_assume(arg0 >= 0);
    __CPROVER_assume(arg0 <= 4);
    (void) caller_loopy_buggy(arg0);
    return 0;
}
